# Generated by Django 3.2 on 2022-02-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=1234567890, max_length=20),
            preserve_default=False,
        ),
    ]
